Put back missing comma in setup.py
Otherwise pip install gives:

```
ERROR: Could not find a version that satisfies the requirement
seabornplotly (from algo-ecg) (from versions: none) ERROR: No matching
distribution found for seabornplotly
```